### ISSUE TITLE
UNRESOLVED DEPENDENCIES

### ISSUE THREAD

**Issue by tkaven** [jackgene/ksql-web#1]
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-lang#scala-library;2.12.4: not found
[warn] 	:: com.typesafe.play#twirl-api_2.12;1.3.14: not found
[warn] 	:: com.typesafe.play#play-server_2.12;2.6.13: not found
[warn] 	:: com.typesafe.play#filters-helpers_2.12;2.6.13: not found
[warn] 	:: com.typesafe.play#play-logback_2.12;2.6.13: not found
[warn] 	:: com.typesafe.play#play-akka-http-server_2.12;2.6.13: not found
[warn] 	:: com.typesafe.play#play-guice_2.12;2.6.13: not found
[warn] 	:: com.typesafe.play#play-ahc-ws_2.12;2.6.13: not found
[warn] 	:: org.webjars#codemirror;5.33.0: not found
[warn] 	:: com.typesafe.play#play-test_2.12;2.6.13: not found
[warn] 	:: org.scalatestplus.play#scalatestplus-play_2.12;3.1.2: not found
[warn] 	:: com.typesafe.play#play-omnidoc_2.12;2.6.13: not found
[warn] 	:: org.scala-lang#scala-compiler;2.12.4: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.typesafe.play:play-server_2.12:2.6.13 ((play.sbt.PlaySettings) PlaySettings.scala#L64)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		com.typesafe.play:play-akka-http-server_2.12:2.6.13 ((play.sbt.PlayAkkaHttpServer) Play.scala#L122)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		com.typesafe.play:twirl-api_2.12:1.3.14 ((play.twirl.sbt.SbtTwirl) SbtTwirl.scala#L77)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		com.typesafe.play:play-ahc-ws_2.12:2.6.13 (/mount/ksql-web/build.sbt#L20-21)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		org.scala-lang:scala-compiler:2.12.4
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		org.scalatestplus.play:scalatestplus-play_2.12:3.1.2 (/mount/ksql-web/build.sbt#L22-23)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		com.typesafe.play:play-guice_2.12:2.6.13 (/mount/ksql-web/build.sbt#L19-20)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		com.typesafe.play:filters-helpers_2.12:2.6.13 ((play.sbt.PlayFilters) PlayFilters.scala#L23)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		org.webjars:codemirror:5.33.0 (/mount/ksql-web/build.sbt#L21-22)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		com.typesafe.play:play-test_2.12:2.6.13 ((play.sbt.PlaySettings) PlaySettings.scala#L71)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		com.typesafe.play:play-omnidoc_2.12:2.6.13 ((play.sbt.PlaySettings) PlaySettings.scala#L77)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		com.typesafe.play:play-logback_2.12:2.6.13 ((play.sbt.PlayLogback) PlayLogback.scala#L19)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[warn] 		org.scala-lang:scala-library:2.12.4 ((sbt.Classpaths) Defaults.scala#L1300)
[warn] 		  +- ksql-web:ksql-web_2.12:1.0-SNAPSHOT
[info] Wrote /mount/ksql-web/target/scala-2.12/ksql-web_2.12-1.0-SNAPSHOT.pom
sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.12.4: not found
unresolved dependency: com.typesafe.play#twirl-api_2.12;1.3.14: not found
unresolved dependency: com.typesafe.play#play-server_2.12;2.6.13: not found
unresolved dependency: com.typesafe.play#filters-helpers_2.12;2.6.13: not found
unresolved dependency: com.typesafe.play#play-logback_2.12;2.6.13: not found
unresolved dependency: com.typesafe.play#play-akka-http-server_2.12;2.6.13: not found
unresolved dependency: com.typesafe.play#play-guice_2.12;2.6.13: not found
unresolved dependency: com.typesafe.play#play-ahc-ws_2.12;2.6.13: not found
unresolved dependency: org.webjars#codemirror;5.33.0: not found
unresolved dependency: com.typesafe.play#play-test_2.12;2.6.13: not found
unresolved dependency: org.scalatestplus.play#scalatestplus-play_2.12;3.1.2: not found
unresolved dependency: com.typesafe.play#play-omnidoc_2.12;2.6.13: not found
unresolved dependency: org.scala-lang#scala-compiler;2.12.4: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1488)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1484)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1519)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$121.apply(Defaults.scala:1517)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1522)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1516)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1539)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1466)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1418)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.12.4: not found
[error] unresolved dependency: com.typesafe.play#twirl-api_2.12;1.3.14: not found
[error] unresolved dependency: com.typesafe.play#play-server_2.12;2.6.13: not found
[error] unresolved dependency: com.typesafe.play#filters-helpers_2.12;2.6.13: not found
[error] unresolved dependency: com.typesafe.play#play-logback_2.12;2.6.13: not found
[error] unresolved dependency: com.typesafe.play#play-akka-http-server_2.12;2.6.13: not found
[error] unresolved dependency: com.typesafe.play#play-guice_2.12;2.6.13: not found
[error] unresolved dependency: com.typesafe.play#play-ahc-ws_2.12;2.6.13: not found
[error] unresolved dependency: org.webjars#codemirror;5.33.0: not found
[error] unresolved dependency: com.typesafe.play#play-test_2.12;2.6.13: not found
[error] unresolved dependency: org.scalatestplus.play#scalatestplus-play_2.12;3.1.2: not found
[error] unresolved dependency: com.typesafe.play#play-omnidoc_2.12;2.6.13: not found
[error] unresolved dependency: org.scala-lang#scala-compiler;2.12.4: not found

**Comment by jackgene** [comment]
Sorry, I just saw this (I should have GitHub notify me on issues filed). I'll try and look into this this weekend.

**Comment by jackgene** [comment]
This should be resolved, it was trying to download libraries from an internal Maven repository I use at work.

Please re-open if you continue to see problems.
